name: Nx Affected CI
on:
  pull_request:
    branches: [main]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: install Cypress from cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: cd node_modules/cypress && yarn run postinstall
      - run: npx nx affected --target=test --parallel=5 --runner=ci
        env:
          STORYBOOK_NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.STORYBOOK_NEXT_PUBLIC_SANITY_PROJECT_ID  }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID  }}
      - run: npx nx affected --target=e2e --parallel=5 --runner=ci
        env:
          STORYBOOK_NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.STORYBOOK_NEXT_PUBLIC_SANITY_PROJECT_ID  }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID  }}
